export const NATIVE_USAGE_ICONS: Readonly<Record<string, string>> = {
  antigravity: "icons/antigravity.svg",
  "claude-statusline": "icons/anthropic.svg",
  claude: "icons/anthropic.svg",
  codex: "icons/openai.svg",
  cursor: "icons/cursor.svg",
  "deepseek-rate": "icons/deepseek.svg",
  deepinfra: "icons/deepinfra.svg",
  deepseek: "icons/deepseek.svg",
  siliconflow: "icons/siliconflow.svg",
  "github-copilot": "icons/github-copilot.svg",
  grok: "icons/grok.svg",
  minimax: "icons/minimax.svg",
  "minimax-cn": "icons/minimax.svg",
  kimi: "icons/moonshot.svg",
  moonshot: "icons/moonshot.svg",
  "moonshot-cn": "icons/moonshot.svg",
  novita: "icons/novita.svg",
  "openrouter-credits": "icons/openrouter.svg",
  openrouter: "icons/openrouter.svg",
  "opencode-go": "icons/opencode.svg",
  "opencode-zen": "icons/opencode.svg",
  stepfun: "icons/stepfun.svg",
  "stepfun-ai": "icons/stepfun.svg",
  vercel: "icons/vercel.svg",
  zenmux: "icons/zenmux.svg",
  xai: "icons/xai.svg",
};

export const NATIVE_USAGE_FALLBACK_ICON = "icons/usage-monitor.svg";
